/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Persons } from "./Persons";
export * as factories from "./factories";
export { Persons__factory } from "./factories/Persons__factory";
